Id b 4.3
Andrey666Berkov/PetFamily pull request #5
Opened 2024-09-10 07:32 UTC by Andrey666Berkov

2024-09-10 09:13 UTC, YADARAN1 commented on backend/src/PetFamily.Domain/Modules/ListRequisites.cs
> +    public List<SocialNetwork> SocialNetwork{ get; private set; }
И лучше раздели по разным обёрткам

2024-09-10 09:15 UTC, YADARAN1 commented on backend/src/PetFamily.Domain/Modules/Pet.cs
> +    public static Result<Pet> CreatePet(PetId petid, string nickName, string discription,
Тут тоже

2024-09-10 09:15 UTC, YADARAN1 commented on backend/src/PetFamily.Domain/Modules/Pet.cs
> +            return Result<Pet>.Failure("Discription is not null or empty");
Везде добавить отступы

2024-09-10 09:16 UTC, YADARAN1 commented on backend/src/PetFamily.Domain/Modules/Pet.cs
> +    public ListRequisites Requisites { get; private set; }
Нам не нужно указывать тут обёртку и у животного нет соц.сетей, они только у волонтёра

2024-09-10 09:16 UTC, YADARAN1 commented on backend/src/PetFamily.Domain/Modules/Pet.cs
> +    public PetListPhoto? Photos { get; private set; }
И здесь также

2024-09-10 09:26 UTC, YADARAN1 commented on backend/src/PetFamily.Domain/Modules/Pet.cs
> +        var req=Requisites.Requisites
Этот метод для удаления удалить

2024-09-10 09:27 UTC, YADARAN1 commented on backend/src/PetFamily.Domain/Modules/Pet.cs
> +            Requisites.Requisites.Remove(req);
И ниже SetProperty тоже убрать

2024-09-10 09:27 UTC, YADARAN1 commented on backend/src/PetFamily.Domain/Modules/Pet.cs
> +        Requisites.Requisites.Add(requisite);
![image](https://github.com/user-attachments/assets/30a736ee-2ba8-4ee8-9ae1-0d7a133c978c)

Тут должно быть так

2024-09-10 09:29 UTC, YADARAN1 commented on backend/src/PetFamily.Domain/Modules/PetId.cs
> +            string.IsNullOrWhiteSpace(city) ||
Разделить проверку для всех свойств, сделать нормальную валидацию с отступами

2024-09-10 09:30 UTC, YADARAN1 commented on backend/src/PetFamily.Domain/Modules/PetListPhoto.cs
> +    public List<PetPhoto> Photos { get; private set; }
private set убрать

2024-09-10 09:30 UTC, YADARAN1 commented on backend/src/PetFamily.Domain/Modules/PetPhoto.cs
> +            return Result<PetPhoto>.Failure("PathToStorage cannot be empty");
Отступы

2024-09-10 09:30 UTC, YADARAN1 commented on backend/src/PetFamily.Domain/Modules/PetPhoto.cs
> +    private PetPhoto(string pathToStorage,
Так не писать, в 1 строку нормально вмещается

2024-09-10 09:30 UTC, YADARAN1 commented on backend/src/PetFamily.Domain/Modules/PetPhoto.cs
> +    public static Result<PetPhoto> Create(string pathToStorage,
Тут тоже

2024-09-10 09:30 UTC, YADARAN1 commented on backend/src/PetFamily.Domain/Modules/Requisite.cs
> +            return Result<Requisite>.Failure("Title or description cannot be empty");
Отступы

2024-09-10 09:31 UTC, YADARAN1 commented on backend/src/PetFamily.Domain/Modules/SocialNetwork.cs
> +public class SocialNetwork
Класс заменить на рекорд

2024-09-10 09:31 UTC, YADARAN1 commented on backend/src/PetFamily.Domain/Modules/SocialNetwork.cs
> +    public string Link { get; private set; }= default!;
private set убрать у обоих свойств

2024-09-10 09:31 UTC, YADARAN1 commented on backend/src/PetFamily.Domain/Modules/PetId.cs
> +public record PetId
Вынести в отдельный файл

2024-09-10 09:31 UTC, YADARAN1 commented on backend/src/PetFamily.Domain/Modules/Volunteer.cs
> +public record VolunteerId
Вынести в отдельный файл

2024-09-10 09:32 UTC, YADARAN1 commented on backend/src/PetFamily.Domain/Modules/Volunteer.cs
> +    public ListRequisites Requisites { get; private set; }
Вернуть как было

2024-09-10 09:32 UTC, YADARAN1 commented on backend/src/PetFamily.Domain/Modules/Volunteer.cs
> +    public ListSocialNetwork SocialNetwork { get; private set; }
Тут тоже

2024-09-10 09:32 UTC, YADARAN1 commented on backend/src/PetFamily.Domain/Modules/Volunteer.cs
> +    private Volunteer(VolunteerId id,string firstName, string lastName,
1 параметр на 1 строке

2024-09-10 09:32 UTC, YADARAN1 commented on backend/src/PetFamily.Domain/Modules/Volunteer.cs
> +    public string RemoveRequisites(Requisite requisite)
Удалить

2024-09-10 09:33 UTC, YADARAN1 commented on backend/src/PetFamily.Domain/Modules/Volunteer.cs
> +            return Result<Volunteer>.Failure("FirstName is not null or empty");
Отступы

2024-09-10 09:34 UTC, YADARAN1 commented on backend/src/PetFamily.Domain/Modules/Volunteer.cs
> +    public static Result<Volunteer> CreateVolunteer(VolunteerId id,string firstName, string lastName,
1 параметр на 1 строке

2024-09-10 09:34 UTC, YADARAN1 commented on backend/src/PetFamily.Domain/Modules/PetId.cs
> +// public class ID<T> where T : class
Удалить

2024-09-10 09:36 UTC, YADARAN1 commented on backend/src/PetFamily.Domain/Modules/Volunteer.cs
> +    public void AddRequisites(Requisite requisite)
![image](https://github.com/user-attachments/assets/fc05d516-4ba6-4961-b921-d2556244d6f0)

2024-09-10 09:36 UTC, YADARAN1 commented on backend/src/PetFamily.Domain/Modules/Volunteer.cs
> +    public static Result<Volunteer> CreateVolunteer(VolunteerId id,string firstName, string lastName,
SetProperty удалить метод

2024-09-10 09:37 UTC, YADARAN1 commented on backend/src/PetFamily.Domain/Shared/Result.cs
> +  public Tvalue Value => IsSuccess ?
Поправить табуляцию и добавить отступы

2024-09-10 09:38 UTC, YADARAN1 commented on backend/src/PetFamily.Infrastructure/ApplicationDbContext.cs
> +    public DbSet<Pet> Pets { get; set; } = null!;
DbSet животного удалить, волонтёр у нас агрегат

2024-09-10 09:38 UTC, YADARAN1 commented on backend/src/PetFamily.Infrastructure/Configuration/PetConfiguration.cs
> +        builder.ToTable("Pets");
Отступы во всей конфигурации и название с маленькой буквы в snakecase стиле

2024-09-10 09:39 UTC, YADARAN1 commented on backend/src/PetFamily.Infrastructure/Configuration/VolunteerConfiguration.cs
> +        builder.ToTable("Volunteers");
Отступы во всей конфигурации и название с маленькой буквы в snakecase стиле

2024-09-10 09:40 UTC, YADARAN1 commented on backend/src/PetFamily.Infrastructure/Configuration/PetConfiguration.cs
> +            po.ToJson();
В скобках добавить название в snakecase стиле

2024-09-10 09:40 UTC, YADARAN1 commented on backend/src/PetFamily.Infrastructure/Configuration/PetConfiguration.cs
> +            po.ToJson();
В скобках добавить название в snakecase стиле

2024-09-10 09:41 UTC, YADARAN1 commented on backend/src/PetFamily.Infrastructure/Configuration/VolunteerConfiguration.cs
> +            po.ToJson();
В скобках добавить название в snakecase стиле

2024-09-10 09:41 UTC, YADARAN1 commented on backend/src/PetFamily.Infrastructure/Configuration/VolunteerConfiguration.cs
> +            po.ToJson();
В скобках добавить название в snakecase стиле

2024-09-12 14:36 UTC, YADARAN1 requested changes

2024-09-12 14:36 UTC, YADARAN1 commented on backend/src/PetFamily.Infrastructure/Configuration/VolunteerConfiguration.cs
> +
У волонтёра добавить связь один ко многим с животным

2024-09-12 14:36 UTC, YADARAN1 commented on backend/src/PetFamily.Infrastructure/PetFamily.Infrastructure.csproj
> +      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.8">
Design мы устанавливаем в слой с API, его нужно переместить обратно

2024-09-12 16:22 UTC, YADARAN1 requested changes

2024-09-12 16:22 UTC, YADARAN1 commented on backend/src/PetFamily.Domain/Modules/Entity/Pet.cs
> +        SpeciesId speciesId,
Это должен быть отдельный VO содержащий в себе SpeciesId speciesId и Guid breedId

2024-09-13 06:08 UTC, Asasen1 commented on backend/src/PetFamily.Domain/Modules/Entity/Pet.cs
> +public sealed class Pet : Entity<PetId>
Зачем seald?

2024-09-13 06:19 UTC, Asasen1 approved these changes

2024-09-13 06:19 UTC, Asasen1 commented on backend/src/PetFamily.Domain/Modules/Entity/Pet.cs
> +    public PetId Id { get; private set; }
У тебя id есть в entity

2024-09-13 06:19 UTC, Asasen1 commented on backend/src/PetFamily.Domain/Modules/Entity/Species.cs
> +    public SpeciesId Id { get; private set; }
Тоже самое

2024-09-13 06:37 UTC, merged